version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: api_container
    commad: python3.12 main.py
    ports:
      - "6099:6099"
    networks:
      - app_network
    depends_on:
      - postgres
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - app_network


volumes:
  postgres_data:

networks:
  app_network:

