name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubunti-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        echo "FASTAPI_DB_URL=${{ secrets.FASTAPI_DB_URL }}" >> .env
        echo "FASTAPI_REDIS_URL=${{ secrets.FASTAPI_REDIS_URL }}" >> .env
        echo "FASTAPI_RABBITMQ_BROCKER=${{ secrets.FASTAPI_RABBITMQ_BROCKER }}" >> .env
        echo "FASTAPI_RABBITMQ_BACKEND=${{ secrets.FASTAPI_RABBITMQ_BACKEND }}" >> .env
        echo "FASTAPI_OPENAI_API=${{ secrets.FASTAPI_OPENAI_API }}" >> .env
        echo "FASTAPI_XML_URL=${{ secrets.FASTAPI_XML_URL }}" >> .env
        cp .env src/.env

    - name: Run Tests
      run: |
        pytest -v

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        echo "FASTAPI_DB_URL=${{ secrets.FASTAPI_DB_URL }}" >> .env
        echo "FASTAPI_REDIS_URL=${{ secrets.FASTAPI_REDIS_URL }}" >> .env
        echo "FASTAPI_RABBITMQ_BROCKER=${{ secrets.FASTAPI_RABBITMQ_BROCKER }}" >> .env
        echo "FASTAPI_RABBITMQ_BACKEND=${{ secrets.FASTAPI_RABBITMQ_BACKEND }}" >> .env
        echo "FASTAPI_OPENAI_API=${{ secrets.FASTAPI_OPENAI_API }}" >> .env
        echo "FASTAPI_XML_URL=${{ secrets.FASTAPI_XML_URL }}" >> .env
        cp .env src/.env

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          set -e
          cd deploy
          git pull origin main
          cp $GITHUB_WORKSPACE/.env .env
          cp $GITHUB_WORKSPACE/src/.env src/.env
          docker-compose down
          docker-compose up --build -d

